### PR TITLE
Remove comments that are only relevant to the FSL implementation

### PR DESCRIPTION
**Pull request by fabianp**
Closes # .

Changes proposed in this pull request:

- Remove comments that are only relevant to the FLS implementation
-

### CODE REVIEW

**Comment by fabianp** [comment]
CC @CesarCaballeroGaudes

**Comment by eurunuela** [comment]
I think you mean FSL @fabianp?

**Comment by fabianp** [comment]
indeed, fixed

**Review by eurunuela — APPROVED** [review]
LGTM!

**Pull request merged**
