### PR TITLE
[ENH] Generate BIDS Derivatives-compatible outputs

### LINKED ISSUE #5: Produce BIDS Derivatives-compatible outputs
We have a set of outputs of interest from AROMA, including:

- Denoised 4D image, in native and standard space (possibly)
- Metrics (feature scores)
- Component time series
- Component maps, in native and standard space (possibly)
- Classifications (included with feature scores in "classification_overview.txt")
- Figure

We should figure out how best to make those outputs BIDS Derivatives-compatible.

At minimum, I think we can use filenames that are basically BIDS-ish, like what I propose in https://github.com/ME-ICA/tedana/pull/574. This means using entities and suffixes that match BIDS convention, minus the "source entities" from the original files (e.g., `sub`, `ses`, `run`).

I don't know if we want to output the classifications/metrics as a json (as in `tedana`) or a tsv. A tsv would be easier to read...

### PR DESCRIPTION
**Pull request by tsalo**
Closes #5.

Changes proposed in this pull request:

- Restructure outputs to match proposed structure in #5, ME-ICA/tedana#649, and ME-ICA/tedana#574.

TODO:

- [x] Update tests
- [ ] Column names
- [ ] Ingestion of BIDS-Derivatives MELODIC outputs
- [ ] BIDS-Derivatives-compatible MELODIC interface?

### CODE REVIEW

**Comment by tsalo** [comment]
I honestly don't remember what I meant by "Column names", and I think that the MELODIC outputs will have to wait until a different PR.

**Comment by tsalo** [comment]
I cannot figure out why the classifications are not the same!

**Comment by tsalo** [comment]
Hopefully this will be easier to debug once #48 is merged.

**Comment by tsalo** [comment]
I'm noticing that our artifact path (for the tests, not the docs build) and output directory for the integration test don't match up:

Artifact path for integration tests: /tmp/data
Output dir: /tmp/pytest-of-neuro/pytest-0/development_fmri/development_fmri/out

Probably worth tackling in a new issue.

EDIT: Opened #50.

**Comment by tsalo** [comment]
I'm thinking we should re-generate our test data from `main` so that we have a cleaner comparison here. @eurunuela WDYT?

**Comment by eurunuela** [comment]
> I'm noticing that our artifact path (for the tests, not the docs build) and output directory for the integration test don't match up:
> 
> 
> 
> Artifact path for integration tests: /tmp/data
> 
> Output dir: /tmp/pytest-of-neuro/pytest-0/development_fmri/development_fmri/out
> 
> 
> 
> Probably worth tackling in a new issue.

Is it possible this comes from using the nipype docker image?

I'd try rerunning with the miniconda image first.

**Comment by eurunuela** [comment]
Wanna merge his @tsalo ?

For the record, the problem was we were not using a seed and `feature_time_series` randomizes the selection of the 90% of the rows. I regenerated the benchmark data with a seed in `main`, added the same seed to the integration tests here, and the tests pass now.

Edit: It would be very useful to merge this for #45 because for some reason I cannot replicate the results in this PR.

**Comment by tsalo** [comment]
Sure! Merging now.

**Pull request merged**
