### PR TITLE
Fix `testpath` and configure artifact path accordingly

### LINKED ISSUE #50: Integration test artifacts are not being stored
### Summary
This stems from https://github.com/ME-ICA/aroma/pull/46#issuecomment-931394320. Basically, the path we use in the CircleCI config for `store_artifacts` isn't where the integration tests are writing their outputs to, which means we can't access those outputs.

### Next Steps
1. Figure out the appropriate output directory to use in the integration test.
2. Use that path.
3. Ensure that `store_artifacts` is also pointing to that directory.
4. Check that artifacts are accessible.

### PR DESCRIPTION
**Pull request by vinferrer**
Closes #50 .

Changes proposed in this pull request:

1. fix the `testpath` generated by `tmp_path_factory` to something similar to `/tmp/pytest-0/data`
2. Ensure that store_artifacts is also pointing to that directory.
3. Check that artifacts are accessible.

### CODE REVIEW

**Comment by vinferrer** [comment]
@tsalo, @eurunuela. This PR is ready for review, as you can see now the data directory is uploaded as artifact for the integration tests. I also took the liberty to correct the lintin artifact issue. Even if there is no file now in the artifacts for `style check` job thats because the program detects that the report file is empty because there aren't any lintin problems

**Comment by vinferrer** [comment]
One more thing, make sure to add the hactoberfest label before merging

**Review by eurunuela — APPROVED** [review]
LGTM! Thank you @vinferrer !

**Review by tsalo — APPROVED** [review]
LGTM too. Thanks!

**Pull request merged**
