### PR TITLE
[ENH] Add motion parameter conversion functions

### LINKED ISSUE #6: Add utility functions for working with different types of motion parameters
We can include motion parameter converters for typical outputs, like AfNI, fMRIPrep, and SPM, in addition to the default FSL outputs.

### PR DESCRIPTION
**Pull request by tsalo**
Closes #6 and stems from https://github.com/Brainhack-Donostia/ica-aroma-org/pull/48.

To do:

- [x] Review logic.
- [x] Complete docstrings.
- [x] Add tests.
- [x] Incorporate functions into workflow.

Changes proposed in this pull request:

- Add functions to load motion parameters from different sources, including FSL, AfNI, SPM, and fMRIPrep.

### CODE REVIEW

**Comment by eurunuela** [comment]
Hey @tsalo , thank you for the PR! 

I ran the integration test and it failed. Apparently, there's an issue with the `np.dot()` in line 317 of `utils.py`.

It's an issue with the dimensions of the matrix:

`E   ValueError: shapes (2,44) and (2,) not aligned: 44 (dim 1) != 2 (dim 0)`

Did you have any issues running the code?

**Comment by tsalo** [comment]
@eurunuela I think that is what @vinferrer caught in #33.

**Comment by eurunuela** [comment]
> @eurunuela I think that is what @vinferrer caught in #33.

It is, yes! We went through it together in GatherTown.

**Comment by eurunuela** [comment]
Hey @tsalo . I just merged this branch with `main` and all the tests pass on my computer.

I'm happy to merge this in once you merge with `main`.

Edit: we should add unit tests too.

**Comment by tsalo** [comment]
I will try to get the unit tests done before EOD (for me) Thursday.

EDIT: I lied. Working on it today.

**Pull request merged**
