### PR TITLE
Add docker with FSL for integration tests

### LINKED ISSUE #40: Add FSL image for testing
### Summary
I understand our objective is not u use ``FSL``, however I think that at somepoint we need to setup a test that certifies our AROMA and FSL AROMA to be equivalent. Therefore I propose to find a docker image that can be able to run the integration test that we have now so later is easier to create this compatibility test.

-->
### Next Steps
- Look for an fsl docker image for example: https://hub.docker.com/r/bids/base_fsl/
- Try to run the integration tests on it

### PR DESCRIPTION
**Pull request by eurunuela**
Closes #40 .

Changes proposed in this pull request:

- Add nipype docker to run integration tests with FSL.

### CODE REVIEW

**Comment by vinferrer** [comment]
Try sudo?

**Comment by eurunuela** [comment]
Apparently, the issue is that once the job is finished, the conda environment is removed. Locally, when I exit the docker image and get back in, the conda environment is no longer there. The same thing is happening with CircleCI. 

I have no idea why this is happening with Aroma but it doesn't happen with other repos. I actually use `nipype/nipype` in a repo of mine and have no issues with it.

Any ideas @tsalo @vinferrer ?

**Comment by tsalo** [comment]
Maybe something's wrong with the caching? That _should_ be the step that makes the environment persist within the Docker image, right?

**Comment by eurunuela** [comment]
> Maybe something's wrong with the caching? That _should_ be the step that makes the environment persist within the Docker image, right?

Right. But I honestly do not know how to check what's going wrong with the caching.

**Comment by notZaki** [comment]
I think the environment is still there, but conda is not recognizing it for whatever reason. Maybe it's because the environments are in `/opt/conda` instead of `/opt/miniconda-latest`, but the [cache is using the latter path](https://github.com/eurunuela/aroma/blob/c631582300560f8ef7729771393b53b3fcaf3f10/.circleci/config.yml#L28-L31)? Not really sure what's going on there.

Try using the complete path to the environment when activating it, [like in this commit](https://github.com/notZaki/aroma/commit/6331d5ada08a8770afa27405cde127b8f814058e).

**Comment by eurunuela** [comment]
Wow, thank you @notZaki ! I'm surprised that made the trick. When I tested locally I could see the environment under `miniconda-latest`. I don't know why saving the environment in `miniconda-latest` and reading it from `conda` works. This is pretty weird but it works now. Thank you!

**Comment by eurunuela** [comment]
Well, that was a crazy ride with the conda environments and the environment variables, but it works now!

I would like to know what you think @vinferrer @notZaki @tsalo

**Review by vinferrer — APPROVED** [review]
LGTM!! nicely done @eurunuela

**Review by tsalo — APPROVED** [review]

**Review by notZaki — APPROVED** [review]

**Comment by eurunuela** [comment]
> I think the environment is still there, but conda is not recognizing it for whatever reason. Maybe it's because the environments are in `/opt/conda` instead of `/opt/miniconda-latest`, but the [cache is using the latter path](https://github.com/eurunuela/aroma/blob/c631582300560f8ef7729771393b53b3fcaf3f10/.circleci/config.yml#L28-L31)? Not really sure what's going on there.

It looks like this is not the case in the `main` branch. I will open a PR with a quick fix for it. This is really weird anyway.

**Pull request merged**
